sonar.projectKey=AbdulQader496_URLshortner-microservices
sonar.organization=abdulqader496

sonar.sources=go-service,python-service,node-service
sonar.exclusions=**/node_modules/**,**/*.db,**/vendor/**

sonar.python.version=3.14
sonar.go.coverage.reportPaths=
sonar.javascript.lcov.reportPaths=